// Code generated by protoc-gen-go.
// source: first.proto
// DO NOT EDIT!

/*
Package firstpb is a generated protocol buffer package.

It is generated from these files:
	first.proto

It has these top-level messages:
*/
package firstpb

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

func init() {
}
