// Code generated by protoc-gen-go.
// source: firstpb/first.proto
// DO NOT EDIT!

/*
Package firstpb is a generated protocol buffer package.

It is generated from these files:
	firstpb/first.proto

It has these top-level messages:
*/
package firstpb

import proto "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

func init() {
}

// Client API for FirstService service

type FirstServiceClient interface {
}

type firstServiceClient struct {
	cc *grpc.ClientConn
}

func NewFirstServiceClient(cc *grpc.ClientConn) FirstServiceClient {
	return &firstServiceClient{cc}
}

// Server API for FirstService service

type FirstServiceServer interface {
}

func RegisterFirstServiceServer(s *grpc.Server, srv FirstServiceServer) {
	s.RegisterService(&_FirstService_serviceDesc, srv)
}

var _FirstService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "first.FirstService",
	HandlerType: (*FirstServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
}
